version: '3.3'
services:
  captcha-micro:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: productiond
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      SWAGGER: 'true'
      WEB_PORT: 3000
      HOST_NAME: localhost
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
